### ISSUE TITLE
Github Action Fails due to FTP-Deploy-Action

### ISSUE THREAD

**Issue by stephanbogner** [hfg-gmuend/openmoji.org#169]
@b-g 

FTP-Deploy-Action is causing problems again 😞  And I honestly don't know if there is a fix (I again tried both versions) ...

- When using version 3.1.1 ([docs](https://github.com/SamKirkland/FTP-Deploy-Action/blob/da0d77ff390a13097c60f9b9eb954e503a480d97/README.md)) → Ignores the setting and uploads to `openmoji.org/docs` instead of `openmoji.org`
- When using version 4.3.0 → Fails during upload with error ["Server sent FIN packet unexpectedly"](https://github.com/SamKirkland/FTP-Deploy-Action/issues/197)

For now I manually uploaded the new version but that's not ideal obviously.

#### Version 3.1.1

```
name: 🚀 Publish Website

on:
  push:
    branches:
      - production

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action 
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://openmoji.org/
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./docs/
```

#### Version 4.3.0
```
name: 🚀 Publish Website

on:
  push:
    branches:
      - production

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action 
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: openmoji.org
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./docs/
        server-dir: ./
```
